# service-registry now is using Spring Security, so we need to provide the username and password to access it.
dl:
    serviceRegistry:
        username: admin
        password: 'admin'
        # password: '{cipher}SOME_RANDOM_STRING' # This way I encrypt the 'admin' password, so that I do not expose it when it goes to github.
    auth:
        jwtSecret: NkIP8zxkLUlWkEg8LIS8m6omrUDdYfeTgu7UkfDZoKTmNEP2EAR7Z3574uN0G5CMSYZwk4aAgOwaQhMqCKbPphHaHbXDSrXJp88EBRA8gft6uP8WaAUVT5F1v8cfN3ii4F3tUoX1tOiJYq6PtGrfQJsg9f1YYStdhBw2QjQGljWxRvhuaDPWihAu5pNoKl8fmBRQzjFwrKs1cS868eB6lybZKVCqugj24p1GdtEssMZwnC0nYSjbU9r4rJSo9heCKb7GGyl7KQvLMeHymyLCh4ZrFOrlUBdSSN5VoPzXMJ99C0wtFCoYTVjFdUgy1WcoWJHtqDGcpXETGbqjHaHqfPBMgHRS5REBcqTHkaOkwdhAbf6W0g1lniKat8Zy2QUSnY0VdEkslvoGYphtMhPWssPVAWcmZfkBaYcMCtaBTRcXKwlMf3i69OFOqzYCSF1fv2oTQYBpMmxBfiWaEvxTDe3sijZWAipBDWTeQmZknZX1uAQ5i4DZmJ4XP7CLNmz6
        # jwtSecret: '{cipher}SOME_RANDOM_STRING' # This way I encrypt the 'admin' password, so that I do not expose it.
        # In ms this value below corresponds to 4h
        jwtExpirationMs: 14400000

eureka:
  client:
    serviceUrl:
      defaultZone: 'https://${dl.serviceRegistry.username}:${dl.serviceRegistry.password}@dl-serviceregistry-prod.herokuapp.com/eureka'
  instance:
    hostname: ${APP_DOMAIN_NAME}
    non-secure-port: 80