server:
    port: ${PORT}
    servlet:
        context-path: '/dl-authuser/' # This is the context path for the service. Used in conjunction with the API Gateway that has it mapped in the routes.

spring:
    application:
        name: dl-authuser-service
    datasource:
        url: ${JDBC_DATABASE_URL}
        username: ${JDBC_DATABASE_USERNAME}
        password: ${JDBC_DATABASE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc:
                lob.non_contextual_creation: true
#        show-sql: true
#        properties:
#            hibernate:
#                format_sql: true
#                show_sql: true
    rabbitmq:
        addresses: ${CLOUDAMQP_URL}

# Defining the logging level for the application
#logging:
#    level:
#        com.xpto.distancelearning: TRACE
#        root: INFO
#        org.springframework.web: DEBUG
#        org.hibernate: INFO

dl:
    api:
        url:
#            course: 'http://localhost:8082' # I do not to hardcode the URL anymore and instead use the service name defined in the Eureka.
#            'dl-course-service' is the name of the service defined in spring.application.name in the application.yaml file of the dl-course-service.
            course: 'http://dl-course-service/dl-course'
    broker:
        exchange:
            userEvent: 'dl-userevent'

# This is part of the Global Config Pattern and it is being used on authuser >> RefreshScopeController
authuser:
    refreshscope:
        name: Henrique Fernandes UPDATE!!

# This is related to 'actuator' endpoints
management:
    endpoints:
        web:
            exposure:
                include:
                    - refresh
                    - health

# Configuring the Circuit Breaker with Resilience4j (globally) for the service.
resilience4j:
    circuitbreaker:
        instances:
          circuitBreakerInstance:
            slidingWindowSize: 30
            permittedNumberOfCallsInHalfOpenState: 2
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 2
            waitDurationInOpenState: 30s
            failureRateThreshold: 80
    retry:
        instances:
            retryInstance:
                maxAttempts: 3
                waitDuration: 5s
