server:
    port: 8082
    servlet:
        context-path: '/dl-course/' # This is the context path for the service. Used in conjunction with the API Gateway that has it mapped in the routes.

spring:
    application:
        name: dl-course-service
    datasource:
        url: jdbc:postgresql://localhost:5432/dl-course-v2
        username: postgres
        password: root
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc:
                lob.non_contextual_creation: true
#        show-sql: true
#        properties:
#            hibernate:
#                format_sql: true
#                show_sql: true
    rabbitmq:
        addresses: amqps://dsvvfanu:4FhHf07AACm8Gv1-SoWH337wGN6zGi1P@possum.lmq.cloudamqp.com/dsvvfanu

logging:
    level:
        com.xpto.distancelearning: TRACE
        root: INFO
        org.springframework.web: DEBUG
        org.hibernate: INFO

dl:
    api:
        url:
#            authuser: 'http://localhost:8087'# I do not to hardcode the URL anymore and instead use the service name defined in the Eureka.
#            'dl-authuser-service' is the name of the service defined in spring.application.name in the application.yaml file of the dl-authuser-service.
            authuser: 'http://dl-authuser-service/dl-authuser'
    broker:
        exchange:
            userEventExchange: 'dl-userevent'
        queue:
            userEventQueue:
                name: 'dl.userevent.ms.course'

# This is part of the Global Config Pattern and it is being used on course >> RefreshScopeController
course:
    refreshscope:
        name: Henrique Fernandes COURSE!!

# This is related to 'actuator' endpoints
management:
    endpoints:
        web:
            exposure:
                include:
                    - refresh
                    - health
