server:
    port: 8084
    servlet:
        context-path: '/dl-notification/'

spring:
    application:
        name: dl-notification-service
    datasource:
        url:  jdbc:postgresql://localhost:5432/dl-notification-v2
        username: postgres
        password: root
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc:
                lob.non-contextual-creation: true
        properties:
            hibernate:
                show_sql: true
    output:
        ansi:
            enabled: Always
    rabbitmq:
        addresses: amqps://dsvvfanu:4FhHf07AACm8Gv1-SoWH337wGN6zGi1P@possum.lmq.cloudamqp.com/dsvvfanu

logging:
    level:
        com.xpto.distancelearning: TRACE
        org.springframework.core.env: DEBUG
        root: INFO
        org.springframework.web: DEBUG
        org.hibernate: INFO

dl:
    broker:
        exchange:
            notificationCommandExchange: dl.notificationcommand
        queue:
            notificationCommandQueue:
                name: dl.notificationcommand.ms.notification
        key:
            notificationCommandKey: ms.notification

management:
    endpoints:
        web:
            exposure:
                include:
                    - refresh
                    - health
