server:
    port: ${PORT}
    servlet:
        context-path: '/dl-notification/'

spring:
    application:
        name: dl-notification-service
    datasource:
        url:  ${JDBC_DATABASE_URL}
        username: ${JDBC_DATABASE_USERNAME}
        password: ${JDBC_DATABASE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc:
                lob.non-contextual-creation: true
        properties:
            hibernate:
                show_sql: true
    output:
        ansi:
            enabled: Always
    rabbitmq:
        addresses: ${CLOUDAMQP_URL}

#logging:
#    level:
#        com.xpto.distancelearning: TRACE
#        org.springframework.core.env: DEBUG
#        root: INFO
#        org.springframework.web: DEBUG
#        org.hibernate: INFO

dl:
    broker:
        exchange:
            notificationCommandExchange: dl.notificationcommand
        queue:
            notificationCommandQueue:
                name: dl.notificationcommand.ms.notification
        key:
            notificationCommandKey: ms.notification

management:
    endpoints:
        web:
            exposure:
                include:
                    - refresh
                    - health
